apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-challenge-group2-db-pvc
  namespace: 'tech-challenge-group2'
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 1Gi