apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-group2-soat1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-group2-soat1
  template:
    metadata:
      labels:
        app: tech-challenge-group2-soat1
    spec:
      containers:
        - name: tech-challenge-group2-soat1-container
          image: furin27/tech-challenge-group2:v1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080